/** Video selections are anchored to registered immutable previews, never the latest timeline. */
import { REVIEW_SIDEBAR_CSS } from './review-sidebar-style.js';
export const VIDEO_REVIEW_JS = String.raw`
(() => {
  const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
  const btn=(text,fn)=>{const b=el('button',text);b.type='button';b.onclick=fn;return b;};
  const css=el('style');css.textContent='.video-desk{position:fixed;inset:12px;z-index:110;background:#faf9f5;color:#24231e;border:1px solid #c9c5b9;border-radius:16px;padding:18px;display:flex;flex-direction:column;box-shadow:0 12px 80px #0004}.video-toolbar{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.video-toolbar h2{margin:0 auto 0 0}.video-desk button,.video-desk select{font:14px system-ui;padding:8px;cursor:pointer}.video-layout{display:grid;grid-template-columns:minmax(0,2fr) minmax(280px,1fr);gap:20px;overflow:auto;margin-top:12px}.video-view{min-width:0}.video-frame{position:relative;line-height:0;background:#161616}.video-frame video{display:block;width:100%;max-height:64vh;object-fit:contain}.video-overlay{position:absolute;inset:0;touch-action:none;pointer-events:none}.video-overlay.active{pointer-events:auto;cursor:crosshair}.video-region{position:absolute;border:2px solid #ffc64a;background:#ffc64a22;box-sizing:border-box;pointer-events:none}.video-timeline{width:100%;margin:16px 0}.video-clock{font:14px monospace}.video-comments textarea{box-sizing:border-box;width:100%;min-height:95px;margin:12px 0;font:16px/1.5 system-ui}.video-status{white-space:pre-wrap;font:14px/1.5 system-ui;margin:10px 0;color:#665739}.video-selection,.video-note{padding:12px 0;border-bottom:1px solid #d4d0c7}.video-note p{white-space:pre-wrap;overflow-wrap:anywhere}.video-note button{margin:4px}.video-selection button{margin-left:8px}.video-muted{font-size:13px;color:#69665e}@media(max-width:800px){.video-desk{inset:0;padding:10px}.video-layout{grid-template-columns:1fr}.video-frame video{max-height:45vh}}';document.head.append(css);
  css.textContent += ${JSON.stringify(REVIEW_SIDEBAR_CSS)};
  let desk,review,current,wid,token,video,overlay,timeline,clock,selections=[],start=null,region=null,activeSelection=-1,saving=false,key=null,playEnd=null;
  function togglePlayback(player){if(player.paused){player.play().catch(e=>status('无法开始播放：'+e.message));}else player.pause();}
  document.addEventListener('keydown',e=>{if(!desk||e.code!=='Space'||e.altKey||e.ctrlKey||e.metaKey)return;const target=e.target;if(target.closest('textarea,select,[contenteditable="true"]')||target.matches('input:not([type="range"])'))return;e.preventDefault();e.stopPropagation();if(e.repeat)return;const players=[...desk.querySelectorAll('video')];const player=target.closest('.video-compare-side')?.querySelector('video')||players[0];if(player)togglePlayback(player);},true);
  const api=async(path,options)=>{const r=await fetch(path,options);const v=await r.json();if(!r.ok)throw Error(v.error||'请求失败');return v;};
  const compareCss=el('style');compareCss.textContent='.video-compare-pair{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:18px;margin-top:14px}.video-compare-side{min-width:0}.video-compare-side video{width:100%;max-height:55vh;display:block;background:#161616}.video-compare-side input{width:100%}.video-compare-frame{position:relative;line-height:0}.video-compare-note{white-space:pre-wrap;margin:14px 0}.video-compare-wrap{overflow:auto}.video-link-status{font:14px/1.5 system-ui;margin:10px 0}@media(max-width:800px){.video-compare-pair{grid-template-columns:1fr}.video-compare-side video{max-height:32vh}}';document.head.append(compareCss);
  const busy=value=>{saving=value;desk.querySelectorAll('button,input,select,textarea').forEach(n=>{n.disabled=value;});};
  const url=suffix=>'/api/workflows/'+encodeURIComponent(wid)+'/'+suffix;
  const status=text=>{if(desk)desk.querySelector('.video-status').textContent=text;};
  const stamp=ms=>{const n=Math.max(0,Math.round(ms));return String(Math.floor(n/60000)).padStart(2,'0')+':'+String(Math.floor(n/1000)%60).padStart(2,'0')+'.'+String(n%1000).padStart(3,'0');};
  const dirty=()=>selections.length||start!==null||desk?.querySelector('textarea')?.value;
  const discard=()=>!saving&&(!dirty()||confirm('有未提交批注，放弃这些输入？'));
  const reset=()=>{selections=[];start=null;region=null;activeSelection=-1;key=null;playEnd=null;};
  async function open(){if(desk&&!discard())return;wid=new URLSearchParams(location.search).get('workflowId');if(!wid)return;try{review=await api(url('video-review'));token=(await api('/api/text-session')).token;current=review.previews.find(p=>p.previewId===review.currentPreviewId)||review.previews.at(-1);desk?.remove();reset();desk=el('section',undefined,'video-desk');desk.setAttribute('role','dialog');desk.setAttribute('aria-label','视频审片与批注');window.promoVideoReviewOpen=true;document.body.append(desk);render();}catch(e){alert(e.message);}}
  function render(){
    desk.replaceChildren();const top=el('div',undefined,'video-toolbar');top.append(el('h2','视频审片与批注'));
    const versions=el('select');versions.setAttribute('aria-label','视频版本');review.previews.forEach((p,i)=>{const o=el('option','第 '+(i+1)+' 版 · '+p.previewId+(p.previewId===review.currentPreviewId?' · 当前':''));o.value=p.previewId;o.selected=p.previewId===current?.previewId;versions.append(o);});versions.onchange=()=>{if(!discard()){versions.value=current.previewId;return;}video?.pause();current=review.previews.find(p=>p.previewId===versions.value);reset();render();};
    top.append(versions,btn('检查更新',refresh),btn('关闭',()=>{if(!discard())return;video?.pause();desk.remove();desk=null;window.promoVideoReviewOpen=false;document.getElementById('refresh')?.click();}));desk.append(top,el('div','拖动时间轴打点；标记开始和结束可追加多段；框选后添加到对应选区。','video-status'));
    if(!current){desk.append(el('p','尚未交付实际视频。请让制作端注册审片文件后再审核。'));return;}
    const layout=el('div',undefined,'video-layout'),view=el('div',undefined,'video-view'),comments=el('aside',undefined,'video-comments'),frame=el('div',undefined,'video-frame');
    video=el('video');video.controls=true;video.preload='metadata';video.src=url('video-media/'+encodeURIComponent(current.previewId));video.setAttribute('aria-label','审片视频');overlay=el('div',undefined,'video-overlay');overlay.setAttribute('aria-label','画面框选');frame.append(video,overlay);view.append(frame);
    timeline=el('input');timeline.type='range';timeline.min='0';timeline.max=String(current.durationMs);timeline.step='1';timeline.value='0';timeline.className='video-timeline';timeline.setAttribute('aria-label','视频时间轴');clock=el('div','00:00.000 / '+stamp(current.durationMs),'video-clock');
    let scrubbing=false;timeline.onpointerdown=()=>{scrubbing=true;video.pause();playEnd=null;};timeline.onpointerup=timeline.onpointercancel=()=>{scrubbing=false;};
    timeline.oninput=()=>{playEnd=null;seek(Number(timeline.value));};video.ontimeupdate=()=>{if(!scrubbing)timeline.value=String(Math.round(video.currentTime*1000));clock.textContent=stamp(video.currentTime*1000)+' / '+stamp(current.durationMs);if(playEnd!==null&&video.currentTime*1000>=playEnd){const end=playEnd;playEnd=null;seek(end);}};video.onerror=()=>status('视频无法播放；文件可能已改变或格式不受支持。请重新交付可播放的审片版，不会替换成其他版本。');view.append(timeline,clock,btn('播放 / 暂停（空格）',()=>togglePlayback(video)));
    const controls=el('div',undefined,'video-toolbar');controls.append(btn('添加当前时间点',()=>add(now(),now())),btn('标记开始',()=>{start=now();status('开始位置 '+stamp(start)+'；拖到结束位置后点击“标记结束并添加”。');}),btn('标记结束并添加',()=>{if(start===null)return status('请先标记开始位置。');if(now()<=start)return status('结束位置必须晚于开始位置。');add(start,now());start=null;}),btn('框选画面',()=>{video.pause();overlay.classList.add('active');status('在画面上拖出方框；方框应用于当前选中的选区，或下一次添加的选区。');}),btn('清除方框',()=>{region=null;if(activeSelection>=0)delete selections[activeSelection].region;key=null;draw();selectionList();}));view.append(controls,el('p','框选描述目标位置，不保证移动目标在整段中都被覆盖。制作端需要检查整个所选时间段。','video-muted'));bindRegion();
    comments.append(el('h3','本条意见的选区'),el('div',undefined,'video-selections'));const intent=el('select');intent.setAttribute('aria-label','意见类型');for(const [value,label] of [['production_change','制作修改：剪切、声音、字幕、画面'],['planning_change','策划变更：内容、口播、表达方向']]){const o=el('option',label);o.value=value;intent.append(o);}intent.onchange=()=>{key=null;};const input=el('textarea');input.setAttribute('aria-label','视频批注意见');input.placeholder='希望这里怎样调整？';input.oninput=()=>{key=null;};comments.append(intent,input,btn('保存视频批注',save),btn('取消输入',()=>{if(!discard())return;reset();input.value='';selectionList();draw();}),el('h3','批注与处理结果'),el('div',undefined,'video-notes'));layout.append(view,comments);desk.append(layout);selectionList();notes();
  }
  const now=()=>Math.max(0,Math.min(current.durationMs,Math.round(video.currentTime*1000)));
  function seek(ms){const player=video,slider=timeline,label=clock,duration=current.durationMs;player.pause();player._pendingSeek=Math.max(0,Math.min(duration,ms));const set=()=>{if(player._pendingSeek===null)return;const value=player._pendingSeek;player._pendingSeek=null;player.currentTime=value/1000;slider.value=String(value);label.textContent=stamp(value)+' / '+stamp(duration);};if(player.readyState)set();else{player.removeEventListener('loadedmetadata',player._seekHandler);player._seekHandler=set;player.addEventListener('loadedmetadata',set,{once:true});}}
  function add(a,b){if(selections.length>=32)return status('一条批注最多 32 个选区，请另外创建批注。');selections.push({startMs:a,endMs:b,...(region?{region:{...region}}:{})});activeSelection=selections.length-1;key=null;selectionList();status('选区已添加，可继续追加时间段或填写意见。');}
  function selectionList(){const box=desk.querySelector('.video-selections');box.replaceChildren();selections.forEach((s,i)=>{const row=el('div',(i+1)+'. '+stamp(s.startMs)+(s.endMs!==s.startMs?' — '+stamp(s.endMs):'')+(s.region?' · 已框选':''),'video-selection');row.append(btn('定位 / 选中',()=>{activeSelection=i;region=s.region?{...s.region}:null;seek(s.startMs);draw();}),btn('移除',()=>{selections.splice(i,1);activeSelection=-1;region=null;key=null;selectionList();draw();}));box.append(row);});}
  function bounds(){const r=overlay.getBoundingClientRect(),ratio=(video.videoWidth||16)/(video.videoHeight||9);let w=r.width,h=w/ratio;if(h>r.height){h=r.height;w=h*ratio;}return {left:(r.width-w)/2,top:(r.height-h)/2,width:w,height:h};}
  function draw(){overlay.replaceChildren();if(!region)return;const b=bounds(),r=el('div',undefined,'video-region');r.style.left=(b.left+region.x*b.width)+'px';r.style.top=(b.top+region.y*b.height)+'px';r.style.width=(region.width*b.width)+'px';r.style.height=(region.height*b.height)+'px';overlay.append(r);}
  function bindRegion(){let origin=null;const point=e=>{const r=overlay.getBoundingClientRect(),b=bounds();return{x:Math.max(0,Math.min(1,(e.clientX-r.left-b.left)/b.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top-b.top)/b.height))};};overlay.onpointerdown=e=>{origin=point(e);overlay.setPointerCapture(e.pointerId);};overlay.onpointermove=e=>{if(!origin)return;const p=point(e);region={x:Math.min(origin.x,p.x),y:Math.min(origin.y,p.y),width:Math.abs(p.x-origin.x),height:Math.abs(p.y-origin.y)};draw();};overlay.onpointerup=e=>{if(!origin)return;origin=null;overlay.releasePointerCapture(e.pointerId);overlay.classList.remove('active');if(!region||region.width<.002||region.height<.002){region=null;draw();return status('框选太小，请重新拖动画面选区。');}if(activeSelection>=0)selections[activeSelection].region={...region};key=null;selectionList();status(activeSelection>=0?'已将方框关联到选区 '+(activeSelection+1)+'。':'已框选；请添加时间点或时间段。');};overlay.onpointercancel=()=>{origin=null;overlay.classList.remove('active');};video.onloadedmetadata=draw;}
  async function write(payload){await api(url('video-annotations'),{method:'POST',headers:{'content-type':'application/json','x-promo-token':token},body:JSON.stringify({...payload,expectedRevision:review.revision,idempotencyKey:key||(key=crypto.randomUUID())})});review=await api(url('video-review'));}
  async function save(){if(saving)return;const input=desk.querySelector('textarea');if(current.previewId!==review.currentPreviewId)return status('这是历史版本。请选择当前版并重新选取位置后提交；旧位置不会自动套用。');if(!selections.length)return status('请至少添加一个时间点或时间段。');if(start!==null)return status('还有未完成的时间段，请先标记结束。');if(!input.value.trim())return status('请填写意见。');busy(true);try{await write({action:'create',previewId:current.previewId,sha256:current.sha256,selections,text:input.value,intent:desk.querySelector('[aria-label="意见类型"]').value,unitIds:[]});reset();input.value='';selectionList();draw();notes();status('已保存。制作修改交给 Cutbench；策划变更交给 Promo。');}catch(e){status('未保存，输入已保留：'+e.message);}finally{busy(false);}}
  function locate(previewId,s){if(!discard())return;const target=review.previews.find(p=>p.previewId===previewId);if(!target)return status('找不到对应版本；不会自动使用新版时间位置。');video.pause();current=target;reset();render();region=s?.region||null;seek(s?.startMs||0);draw();if(s&&s.endMs>s.startMs)playEnd=s.endMs;status('正在查看原始绑定版本 '+previewId+'。'+(s?'选区 '+stamp(s.startMs)+' — '+stamp(s.endMs):''));}
  function notes(){const list=desk.querySelector('.video-notes');list.replaceChildren();const labels={open:'待处理',addressed:'已修改，待人工复核',resolved:'人工已确认'};for(const a of review.annotations){const row=el('article',undefined,'video-note');row.dataset.annotationId=a.id;row.append(el('strong',labels[a.status]||a.status),el('p',a.text),el('small',(a.intent==='planning_change'?'策划变更 → Promo':'制作修改 → Cutbench')+' · 原版 '+a.previewId));a.selections.forEach((s,i)=>row.append(btn('回看选区 '+(i+1)+' · '+stamp(s.startMs)+(s.endMs>s.startMs?'—'+stamp(s.endMs):''),()=>locate(a.previewId,s))));if(a.reply)row.append(el('p','处理回复：'+a.reply));if(a.targetPreviewId)row.append(btn('查看修改版',()=>{locate(a.targetPreviewId);status('已打开修改版；旧批注时间不自动套用。请按处理回复检查新位置。');}),btn('双视频对照',()=>compare(a)));if(a.status==='addressed')row.append(btn('确认已解决',()=>transition(a,'resolve')),btn('仍有问题',()=>transition(a,'reopen')));if(a.status==='resolved')row.append(btn('重新打开',()=>transition(a,'reopen')));list.append(row);}if(!review.annotations.length)list.append(el('p','暂无视频批注。'));}
  function compare(a){
    if(!discard())return;
    const original=review.previews.find(p=>p.previewId===a.previewId),target=review.previews.find(p=>p.previewId===a.targetPreviewId);
    if(!original||!target)return status('缺少对应版本，无法对照。');
    video.pause();reset();desk.replaceChildren();const top=el('div',undefined,'video-toolbar');top.append(el('h2','修改前后 · 双视频对照'));desk.append(top,el('div','左侧保留原批注位置；右侧独立定位。两边选好对应起点后，可显式开启联动。','video-status'));
    const wrap=el('div',undefined,'video-compare-wrap'),pair=el('div',undefined,'video-compare-pair'),message=el('div','独立播放：右侧从 00:00 开始，尚未建立时间对应。','video-link-status');let linked=false,leftStart=0,rightStart=0,selection=a.selections[0];
    const makeSide=(p,label,name)=>{const side=el('div',undefined,'video-compare-side'),frame=el('div',undefined,'video-compare-frame'),player=el('video');player.controls=true;player.preload='auto';player.src=url('video-media/'+encodeURIComponent(p.previewId));player.setAttribute('aria-label',name+'视频');const slider=el('input');slider.type='range';slider.min='0';slider.max=String(p.durationMs);slider.step='1';slider.value='0';slider.setAttribute('aria-label',name+'时间轴');const time=el('div','00:00.000 / '+stamp(p.durationMs),'video-clock');side.append(el('h3',label),el('p',p.previewId,'video-muted'),frame,slider,time);frame.append(player);pair.append(side);return{player,slider,time,frame,preview:p};};
    const left=makeSide(original,'修改前 · 原始批注','修改前'),right=makeSide(target,'修改后 · 请自行定位','修改后');right.player.muted=true;
    const stop=()=>{linked=false;left.player.pause();right.player.pause();message.textContent='独立播放：各自的位置保持不变。';};
    const seekSide=(side,ms)=>{const set=()=>{side.player.currentTime=ms/1000;side.slider.value=String(ms);side.time.textContent=stamp(ms)+' / '+stamp(side.preview.durationMs);};if(side.player.readyState)set();else side.player.addEventListener('loadedmetadata',set,{once:true});};
    for(const side of [left,right]){side.slider.oninput=()=>{stop();seekSide(side,Number(side.slider.value));};side.player.ontimeupdate=()=>{side.slider.value=String(Math.round(side.player.currentTime*1000));side.time.textContent=stamp(side.player.currentTime*1000)+' / '+stamp(side.preview.durationMs);if(linked&&side===left){const expected=rightStart+(left.player.currentTime-leftStart);if(expected<0||expected>=right.preview.durationMs/1000){stop();return;}if(Math.abs(right.player.currentTime-expected)>.2)right.player.currentTime=expected;}};side.player.onended=stop;side.player.onerror=()=>{stop();message.textContent='对应版本无法播放。请检查文件，不会替换为其他视频。';};}
    for(const side of [left,right])side.player.addEventListener('pause',()=>{if(linked)stop();});
    const box=el('div',undefined,'video-region');left.frame.append(box);const drawBox=()=>{if(!selection?.region){box.hidden=true;return;}box.hidden=false;const r=selection.region,w=left.player.clientWidth,h=left.player.clientHeight,ratio=(left.player.videoWidth||16)/(left.player.videoHeight||9),cw=Math.min(w,h*ratio),ch=cw/ratio;box.style.left=((w-cw)/2+r.x*cw)+'px';box.style.top=((h-ch)/2+r.y*ch)+'px';box.style.width=(r.width*cw)+'px';box.style.height=(r.height*ch)+'px';};left.player.addEventListener('loadedmetadata',drawBox);const observer=new ResizeObserver(drawBox);observer.observe(left.frame);
    const cleanup=()=>{stop();observer.disconnect();left.player.removeAttribute('src');right.player.removeAttribute('src');left.player.load();right.player.load();};
    top.append(btn('返回批注与确认',()=>{cleanup();current=target;reset();render();}));const controls=el('div',undefined,'video-toolbar');controls.append(btn('从各自当前位置联动播放',async()=>{leftStart=left.player.currentTime;rightStart=right.player.currentTime;linked=true;message.textContent='联动播放：左 '+stamp(leftStart*1000)+' ↔ 右 '+stamp(rightStart*1000)+'。右侧默认静音，避免两路声音重叠。';try{await Promise.all([left.player.play(),right.player.play()]);}catch(e){stop();message.textContent='无法开始播放：'+e.message;}}),btn('暂停并取消联动',stop));
    const anchors=el('div',undefined,'video-toolbar');a.selections.forEach((s,i)=>anchors.append(btn('原批注选区 '+(i+1),()=>{stop();selection=s;seekSide(left,s.startMs);drawBox();})));wrap.append(pair,controls,message,el('p',a.text,'video-compare-note'),el('p','处理回复：'+(a.reply||'尚无'),'video-compare-note'),anchors);desk.append(wrap);seekSide(left,selection?.startMs||0);seekSide(right,0);drawBox();
  }
  async function transition(a,action){if(saving||!discard())return;if(action==='resolve'&&!confirm('确认已看过修改版，这条意见已经解决？'))return;saving=true;key=null;try{await write({action,annotationId:a.id,expectedAnnotationRevision:a.revision,actor:'human',...(a.targetPreviewId?{targetPreviewId:a.targetPreviewId}:{})});notes();status(action==='resolve'?'已记录人工确认。':'已重新打开，等待进一步处理。');}catch(e){status(e.message);}finally{saving=false;key=null;}}
  async function refresh(){if(!discard())return;try{const id=current?.previewId;review=await api(url('video-review'));current=review.previews.find(p=>p.previewId===id)||review.previews.at(-1);reset();video?.pause();render();status('已更新批注，仍保留你选定的视频版本。');}catch(e){status(e.message);}}
  document.addEventListener('click',e=>{if(e.target.closest('[data-video-review]'))open();});window.addEventListener('promo-text-update',()=>{if(desk){const currentStatus=desk.querySelector('.video-status').textContent;if(!currentStatus.includes('收到流程更新'))status(currentStatus+'\n收到流程更新，当前视频和未提交意见保持不变。返回批注后可点击“检查更新”读取新版。');}});window.addEventListener('resize',()=>{if(desk&&overlay)draw();});
})();
`;
