/** Node 6 keeps its production record while the main workflow revisits planning. */
export const VIDEO_PRODUCTION_JS = String.raw`
(() => {
  const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
  const css=el('style');css.textContent='.vp-panel{margin:18px 0;padding:20px;background:#f4f5ef;border:1px solid #ccd6ca;border-radius:10px;font:14px/1.7 "PingFang SC",sans-serif;color:#293b30}.vp-panel h3{font-size:18px;margin:0 0 12px}.vp-panel h4{font-size:14px;margin:16px 0 8px}.vp-stages{display:flex;gap:7px;flex-wrap:wrap;margin:12px 0}.vp-stages span{padding:4px 8px;border:1px solid #d3dbce;border-radius:5px;font-size:12px}.vp-stages .active{background:#315740;color:white}.vp-panel button{background:white;color:#315740;border:1px solid #acbcae;border-radius:6px;padding:7px 10px;margin:5px;font:13px "PingFang SC",sans-serif}.vp-panel textarea,.vp-panel select{box-sizing:border-box;max-width:100%;font:14px/1.6 "PingFang SC",sans-serif;padding:8px;background:white;color:#293b30;border:1px solid #bbc8b9;border-radius:5px}.vp-panel textarea{display:block;width:100%;min-height:66px;margin:10px 0}.vp-task{background:white;margin:6px 0;padding:9px;border-left:3px solid #a8bda8}.vp-message{color:#85562c}.vp-panel details{margin-top:14px}.vp-panel ol{padding-left:22px}';document.head.append(css);
  let panel,view,token,busy=false,confirmation=null;
  const labels={working:'制作中',waiting_material:'等待补素材或解除阻塞',awaiting_review:'等待你审片确认',paused_planning:'暂停，等待策划决定',complete:'六阶段已确认，等待最终交付锁定'};
  const owners={user:'你',cutbench:'CutWorkbench',promo:'Promo'},taskStates={todo:'待处理',doing:'处理中',blocked:'有阻塞',done:'已处理，随本轮验收'};
  const api=async(path,options)=>{const r=await fetch(path,options),v=await r.json();if(!r.ok)throw Error(v.error||'读取失败');return v;};
  const path=()=>'/api/workflows/'+encodeURIComponent(new URLSearchParams(location.search).get('workflowId'))+'/video-production';
  const button=(text,fn)=>{const b=el('button',text);b.type='button';b.onclick=fn;return b;};
  async function act(action,extra={}){if(busy)return;const reason=panel.querySelector('textarea')?.value.trim();if(!reason)return message('请先填写本轮意见、确认依据或返回原因。');const signature=JSON.stringify({action,extra,reason,revision:view.revision});if(['approve','return_planning','resume'].includes(action)&&confirmation!==signature){confirmation=signature;return message('请再次点击同一按钮确认：'+({approve:'确认本轮交付并继续',return_planning:'保存制作现场并返回策划',resume:'按所选受影响阶段恢复制作'})[action]+'。');}confirmation=null;busy=true;try{token??=(await api('/api/text-session')).token;await api(path(),{method:'POST',headers:{'content-type':'application/json','x-promo-token':token},body:JSON.stringify({action,reason,...extra,expectedRevision:view.revision,idempotencyKey:crypto.randomUUID()})});await load(true);if(action==='return_planning')document.getElementById('refresh')?.click();}catch(e){message(e.message);}finally{busy=false;}}
  function message(text){panel?.querySelector('.vp-message')?.replaceChildren(document.createTextNode(text));}
  async function load(force=false){const host=document.getElementById('step-6');if(!host)return;if(!force&&host.querySelector('.vp-panel'))return;const requestedPath=path();try{const next=await api(requestedPath);if(path()!==requestedPath||!host.isConnected)return;view=next;panel?.remove();panel=el('section',undefined,'vp-panel');panel.setAttribute('aria-label','视频制作子流程');const heading=host.querySelector('.step-title');if(heading)heading.after(panel);else host.prepend(panel);render();if(view.production){const placeholder=host.querySelector(':scope > .placeholder');if(placeholder)placeholder.hidden=true;if(view.production.status==='paused_planning'){const state=heading?.querySelector('.state');if(state)state.textContent='已暂停，制作现场保留';}}}catch(e){if(panel?.isConnected)message(e.message);}}
  function render(){const p=view.production;panel.append(el('h3','逐步制作 · 每轮看完再继续'),el('div','', 'vp-message'));if(!p){panel.append(el('p','已有策划和素材从这里开始制作。原稿、分镜和素材计划不需要重填。'));if(view.workflowState==='PRODUCING')panel.append(el('textarea'),button('开始素材检查',()=>act('start')));else panel.append(el('p','前面节点确认后，这里会建立常驻制作记录。'));return;}
    const stages=el('div',undefined,'vp-stages');view.phases.forEach(s=>stages.append(el('span',(p.approvals.some(a=>a.phase===s.id)?'✓ ':'')+s.label,s.id===p.phase?'active':'')));panel.append(stages,el('strong','第 '+p.round+' 轮 · '+labels[p.status]));const phase=view.phases.find(s=>s.id===p.phase);panel.append(el('p',phase.instruction),el('h4','本步交付'),el('p',phase.output),el('h4','你要看什么'));const checks=el('ul');phase.checks.forEach(c=>checks.append(el('li',c)));panel.append(checks,el('h4','当前子任务'));const tasks=p.tasks.filter(t=>t.phase===p.phase);tasks.forEach(t=>panel.append(el('div',t.title+' · '+owners[t.owner]+' · '+taskStates[t.status],'vp-task')));if(!tasks.length)panel.append(el('p','请让 Agent 读取制作现场，将本阶段拆成可处理、可验收的任务。'));
    if(p.submission){panel.append(el('p','待确认版本：'+(p.submission.previewId||'素材制品')+' · '+p.submission.note));p.submission.artifactIds.forEach(id=>panel.append(el('small',id+' ')));if(p.submission.previewId){const v=el('video');v.controls=true;v.preload='metadata';v.style.width='100%';v.src='/api/workflows/'+encodeURIComponent(view.workflowId)+'/video-media/'+encodeURIComponent(p.submission.previewId);panel.append(v);const b=button('打开视频批注',()=>{});b.dataset.videoReview='';panel.append(b);}}
    for(const a of view.submissionArtifacts||[]){const d=el('details');d.append(el('summary','查看交付物 · '+a.artifactId));const pre=el('pre',JSON.stringify(a.content,null,2));pre.style.cssText='white-space:pre-wrap;overflow-wrap:anywhere;max-height:280px;overflow:auto;font:13px/1.7 monospace';d.append(pre);panel.append(d);}
    const unresolved=view.videoReview.annotations.filter(a=>a.status!=='resolved');if(unresolved.length){panel.append(el('p','还有 '+unresolved.length+' 条视频意见待解决，本轮不能通过。'));const b=button('查看待处理视频意见',()=>{});b.dataset.videoReview='';panel.append(b);}
    if(p.planningReturn)panel.append(el('p','已保存制作现场，返回第 '+p.planningReturn.node+' 节点：'+p.planningReturn.reason));
    const input=el('textarea');input.placeholder='确认依据 / 修改意见 / 返回原因';input.setAttribute('aria-label','制作流程意见');panel.append(input);
    const select=el('select');select.setAttribute('aria-label','最早受影响阶段');view.phases.slice(0,view.phases.findIndex(s=>s.id===p.phase)+1).forEach(s=>{const o=el('option',s.label);o.value=s.id;o.selected=s.id===p.phase;select.append(o);});panel.append(select);
    if(view.workflowState==='PRODUCING'){if(p.status==='paused_planning')panel.append(button('确认影响并恢复制作',()=>act('resume',{phase:select.value})));else{if(p.status==='awaiting_review')panel.append(button('确认本版并继续',()=>act('approve',{submissionId:p.submission.id})));panel.append(button('按所选阶段返工',()=>act('rework',{phase:select.value})));const node=el('select');node.setAttribute('aria-label','返回策划节点');[[2,'核心诉求'],[3,'创意大纲'],[4,'主稿分镜'],[5,'素材计划']].forEach(([id,label])=>{const o=el('option',label);o.value=String(id);node.append(o);});panel.append(node,button('保存现场并返回策划',()=>act('return_planning',{node:Number(node.value)})));}}else panel.append(el('p','请先完成主流程中的策划和人工确认，再恢复制作。'));
    panel.append(button('更新制作记录',()=>{if(!input.value||confirm('丢弃未提交意见并更新？'))load(true);}));const history=el('details');history.append(el('summary','返工与确认记录（'+p.history.length+'）'));const rows=el('ol');const actions={task:'更新任务',submit:'提交审片',approve:'人工确认',rework:'返工',return_planning:'返回策划',resume:'恢复制作'};p.history.slice().reverse().forEach(h=>rows.append(el('li',h.at+' · '+(actions[h.action]||h.action)+' · '+h.reason)));history.append(rows);panel.append(history);
  }
  new MutationObserver(()=>load()).observe(document.getElementById('app'),{childList:true});window.addEventListener('promo-text-update',()=>message('流程已有更新；当前输入保留，点击“更新制作记录”查看。'));load();
})();`;
